# Generated by Django 3.2.6 on 2021-12-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img1',
            field=models.CharField(default='null', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='img2',
            field=models.CharField(default='null', max_length=2048),
            preserve_default=False,
        ),
    ]
